name: Upload website to S3

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read  # Required for OIDC authentication

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Configure AWS Credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::430118836047:role/GithubOIDC
          aws-region: 'eu-west-2'

      - name: Sync site to S3 with AWS CLI
        run: |
          aws s3 sync iPortfolio-1.0.0 s3://$AWS_S3_BUCKET --acl private --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}

      - name: Invalidate CloudFront Cache
        run: |
          aws cloudfront create-invalidation --distribution-id E5CBP25AF87Q3 --paths "/*"
        env:
          AWS_REGION: 'eu-west-2'
